//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xcicman_zadanie__WAN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xcicman_zadanie__WAN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezvolili ste adaptér pre oba porty alebo ste nezadali IP/MASK.
        /// </summary>
        internal static string Alert1 {
            get {
                return ResourceManager.GetString("Alert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezvolili ste adaptér pre oba porty alebo ste nezadali IP/MASK.
        /// </summary>
        internal static string Allert1 {
            get {
                return ResourceManager.GetString("Allert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nezvolili ste oba adaptére alebo ste nezadali celú IP adresu.
        /// </summary>
        internal static string Allert2 {
            get {
                return ResourceManager.GetString("Allert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose adapter for port..
        /// </summary>
        internal static string chose1 {
            get {
                return ResourceManager.GetString("chose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijal som ICMP  ECHO.
        /// </summary>
        internal static string ICMP___echo {
            get {
                return ResourceManager.GetString("ICMP - echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijal som ICMP a je pre mna.
        /// </summary>
        internal static string ICMP___R {
            get {
                return ResourceManager.GetString("ICMP - R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP - nasiel som zhodu v ARP table.
        /// </summary>
        internal static string ICMP___zhoda_ {
            get {
                return ResourceManager.GetString("ICMP - zhoda ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP - nasiel som zhodu v ARP table.
        /// </summary>
        internal static string ICMP___zhoda_ARP {
            get {
                return ResourceManager.GetString("ICMP - zhoda ARP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP - nenasiel som zhodu v ARP table posielam request.
        /// </summary>
        internal static string ICMP___zhodaN {
            get {
                return ResourceManager.GetString("ICMP - zhodaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICMP - nasiel som zhodu v ARP table.
        /// </summary>
        internal static string Receive_PacketHandler1_ICMP___nasiel_som_zhodu_v_ARP_table {
            get {
                return ResourceManager.GetString("Receive_PacketHandler1_ICMP___nasiel_som_zhodu_v_ARP_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijal som ICMP a je pre mna.
        /// </summary>
        internal static string Receive_PacketHandler1_Prijal_som_ICMP_a_je_pre_mna {
            get {
                return ResourceManager.GetString("Receive_PacketHandler1_Prijal_som_ICMP_a_je_pre_mna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smerujem .
        /// </summary>
        internal static string smerovanie {
            get {
                return ResourceManager.GetString("smerovanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasiel som zhodu v rout table.
        /// </summary>
        internal static string ZhodaN {
            get {
                return ResourceManager.GetString("ZhodaN", resourceCulture);
            }
        }
    }
}
